trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    python -m pip install --upgrade pip
    pip install qrcode[pil]
  displayName: 'Install dependencies'

- script: |
    generate_qr.py
  displayName: 'Generate QR code'
